language: node_js
cache: npm

notifications:
  email:
    on_success: never
    on_failure: always

node_js:
  - node

script:
  - git remote rm origin
  - git remote add origin https://jeetiss:${GITHUB_TOKEN}@github.com/jeetiss/try-release-it.git
  - git checkout master
  - git update-index --assume-unchanged .npmrc
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
  - npm run release -- --ci
