language: node_js
cache: npm

notifications:
  email:
    on_success: never
    on_failure: always

node_js:
  - node

script:
  - git update-index --assume-unchanged .npmrc
  - git branch -u origin/master
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
  - npm run release -- --ci
