language: node_js
cache: npm

notifications:
  email:
    on_success: never
    on_failure: always

node_js:
  - node
git:
  depth: 5

before_deploy:
  - npm run release -- --ci

deploy:
  provider: npm
  email: jeetiss@ya.ru
  api_key: $NPM_TOKEN
