language: node_js
cache: npm

notifications:
  email:
    on_success: never
    on_failure: always

node_js:
  - node
git:
  depth: 5

deploy:
  before_deploy: npm run release -- --ci
  provider: npm
  email: jeetiss@ya.ru
  api_key: $NPM_TOKEN
