language: node_js
cache: npm

notifications:
  email:
    on_success: never
    on_failure: always

node_js:
  - node
git:
  depth: 5

jobs:
  include:
    - stage: test
      script:
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ../.npmrc
        - npm run release -- --ci

stages:
  - test
